export const articles = [
  { id: 1, title: "Building a Real-Time Collaboration Engine with CRDTs", deck: "Conflict-free replicated data types are the secret sauce behind Google Docs and Figma — here's how to implement one from scratch in TypeScript.", author: "Priya Sharma", initials: "PS", verified: true, tags: ["TypeScript", "Distributed Systems"], readTime: 14, publishedAt: "Jul 4, 2025", upvotes: 847, comments: 63, image: "https://images.unsplash.com/photo-1562813733-b31f71025d54?w=900&h=500&fit=crop&auto=format", audio: null },
  { id: 2, title: "How Vercel Rebuilt Their Edge Network from Scratch", deck: "I sat down with Vercel's infrastructure team to talk about why they rebuilt their edge runtime from the ground up — what broke, what they learned, and why they chose Rust.", author: "Priya Sharma", initials: "PS", verified: true, tags: ["podcast", "Infrastructure", "Edge"], readTime: 58, publishedAt: "Jul 3, 2025", upvotes: 612, comments: 41, image: "https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=900&h=500&fit=crop&auto=format", audio: "58 min" },
  { id: 3, title: "Zero to 1M Requests/sec: Scaling Node.js Without a Rewrite", deck: "We took our Express monolith from 10k to 1M requests per second over 18 months using only surgical optimizations at each bottleneck.", author: "Lena Fischer", initials: "LF", verified: true, tags: ["Node.js", "Performance", "System Design"], readTime: 22, publishedAt: "Jul 3, 2025", upvotes: 1204, comments: 147, image: "https://images.unsplash.com/photo-1509966756634-9c23dd6e6815?w=900&h=500&fit=crop&auto=format", audio: null },
  { id: 4, title: "AI Coding Tools in 2025: Copilot vs Cursor vs Claude", deck: "A practical comparison after 6 months using all three in production. No sponsored takes — just my honest breakdown of where each one wins and loses.", author: "Marcus Webb", initials: "MW", verified: false, tags: ["podcast", "AI", "Developer Tools"], readTime: 41, publishedAt: "Jun 26, 2025", upvotes: 891, comments: 73, image: null, audio: "41 min" },
  { id: 5, title: "Postgres Full-Text Search is Probably All You Need", deck: "Before you spin up Elasticsearch, give Postgres tsvector a serious look. It handles most search needs with zero operational overhead.", author: "Sofia Andreeva", initials: "SA", verified: true, tags: ["PostgreSQL", "Backend"], readTime: 9, publishedAt: "Jul 1, 2025", upvotes: 932, comments: 78, image: null, audio: null },
];

export const questions = [
  { id: 1, title: "Cleanest pattern for optimistic UI updates in React Query v5?", author: "Dev Kapoor", initials: "DK", tags: ["React Query", "UX Patterns"], upvotes: 47, answers: 8, views: "1.2k", publishedAt: "3h ago", solved: true },
  { id: 2, title: "How do you structure a Next.js App Router project at scale?", author: "Amara Diallo", initials: "AD", tags: ["Next.js", "Architecture"], upvotes: 89, answers: 14, views: "3.6k", publishedAt: "8h ago", solved: false },
  { id: 3, title: "Is Bun ready for production in 2025? What are the real gotchas?", author: "Yuki Tanaka", initials: "YT", tags: ["Bun", "Runtime"], upvotes: 124, answers: 23, views: "8.9k", publishedAt: "1d ago", solved: true },
];
